import { SessionStatus } from "@prisma/client";
import type { SessionRecord } from "./session-store.js";
import { sessionAnswerUrl } from "./github-service.js";
import { FREE_PLAN_DAILY_QUIZ_LIMIT } from "./marketplace-store.js";
import { BUY_ME_A_COFFEE_URL } from "../constants.js";

export function renderSessionComment(session: SessionRecord): string {
  const lines: string[] = [];

  if (session.status === SessionStatus.quota_exceeded) {
    lines.push(
      `### :white_check_mark: SlopBlock — Passed`,
      "",
      `> This repository has reached the free plan limit of **${FREE_PLAN_DAILY_QUIZ_LIMIT} quiz generations per day**. No quiz was generated for this pull request.`,
      "",
      `:arrow_up: [Support SlopBlock](${BUY_ME_A_COFFEE_URL}) for unlimited daily quiz generations.`,
    );
    return lines.join("\n");
  }

  if (session.status === SessionStatus.skipped) {
    lines.push(
      `### :next_track_button: SlopBlock — Skipped`,
      "",
      `> ${session.skipReason ?? "This pull request matched skip rules."}`,
    );
    return lines.join("\n");
  }

  if (session.status === SessionStatus.passed) {
    lines.push(
      `### :white_check_mark: SlopBlock — Passed`,
      "",
      `Quiz passed for commit \`${session.headSha.slice(0, 7)}\`.`,
    );
    if (session.generationModel || session.validationModel) {
      const models = [
        session.generationModel ? `Generated by \`${session.generationModel}\`` : null,
        session.validationModel ? `Validated by \`${session.validationModel}\`` : null,
      ]
        .filter(Boolean)
        .join(" · ");
      lines.push("", `<sub>${models}</sub>`);
    }
    return lines.join("\n");
  }

  // Awaiting answer
  const questionCount = session.quiz?.questions.length ?? session.questionCount;

  lines.push(
    `### :brain: SlopBlock — ${questionCount} Question${questionCount === 1 ? "" : "s"} Waiting`,
    "",
    `A quiz has been generated from this PR's diff. Answer all questions correctly to pass the check.`,
    "",
    `> :point_right: **[Take the Quiz](${sessionAnswerUrl(session)})**`,
    "",
    `:lock: Only the PR author can submit answers.`,
  );

  if (session.generationModel || session.validationModel) {
    const models = [
      session.generationModel ? `Generated by \`${session.generationModel}\`` : null,
      session.validationModel ? `Validated by \`${session.validationModel}\`` : null,
    ]
      .filter(Boolean)
      .join(" · ");
    lines.push("", `<sub>${models}</sub>`);
  }

  return lines.join("\n");
}
